---
- name: Download k9s
  ansible.builtin.unarchive:
    src: https://github.com/derailed/k9s/releases/download/v{{ k9s_version }}/k9s_Linux_x86_64.tar.gz
    dest: /tmp
    remote_src: true

- name: Install k9s
  ansible.builtin.copy:
    src: /tmp/k9s
    dest: /usr/local/bin/k9s
    owner: root
    group: root
    remote_src: true
    mode: a+x
