---
- name: Create lidarr group
  ansible.builtin.group:
    name: lidarr
    gid: "{{ arr_users['lidarr'].gid }}"

- name: Create lidarr user
  ansible.builtin.user:
    name: lidarr
    uid: "{{ arr_users['lidarr'].uid }}"
    groups: lidarr,{{ arr_group.name }}

- name: Start Lidarr container
  community.docker.docker_container:
    name: lidarr
    image: ghcr.io/linuxserver/lidarr:version-0.7.2.1878
    state: started
    restart_policy: unless-stopped
    networks:
      - name: "{{ traefik_network_name }}"
    volumes:
      - "{{ container_config_folder }}/lidarr:/config"
      - "{{ media_path }}/music:/storage/media/music"
      - "{{ downloads_path }}:/storage/downloads"
    labels:
      traefik.http.routers.lidarr.rule: Host(`lidarr.{{ inventory_hostname }}`)
    env:
      PUID: "{{ arr_users['lidarr'].uid }}"
      PGID: "{{ arr_users['lidarr'].gid }}"
      TZ: "Europe/London"
      UNMASK: "022"
    container_default_behavior: no_defaults
    network_mode: "{{ traefik_network_name }}"
    auto_remove: false
    init: false
    interactive: false
    memory: "0"
    paused: false
    privileged: false
    tty: false
