---
traefik_network_name: traefik

arr_group:
  name: arr
  gid: "709"

arr_users:
  jackett: {uid: 710, gid: 710}
  heimdall: {uid: 711, gid: 711}
  lidarr: {uid: 712, gid: 712}
  plex: {uid: 713, gid: 713}
  radarr: {uid: 714, gid: 714}
  sonarr: {uid: 715, gid: 715}
  tautulli: {uid: 716, gid: 716}
  portainer: {uid: 717, gid: 717}
  transmission: {uid: 718, gid: 718}

container_config_folder: /var/lib/containers
vault_path: /cintra
media_path: "{{ vault_path }}/media"
downloads_path: "{{ vault_path }}/downloads"

vpn_username: "{{ vault_vpn_username }}"
vpn_password: "{{ vault_vpn_password }}"

sql_password: "{{ vault_sql_password }}"

pihole_password: "{{ vault_pihole_password }}"

pihole_static_ip: "192.168.68.121"
ciri_static_ip: "192.168.68.112"
emmas_edit_ip: "{{ vault_emmas_edit_ip }}"

ssh_keys:
  - "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIGOARhByqvHhJYkOvn+1IlEnKsnn3aqNNFXervuw/Qq+ jonny@pattern-2021-03-10"
  - "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIBg5CqPYJjy7SVnvEunrCZv7GrJ/lMih70d4onyTkdMP jonny@ciri-2019-02-12"
