---
- name: Install general development packages
  ansible.builtin.apt:
    name:
      - build-essential
      - yamllint
      - shellcheck
      - cmake
      - ninja-build
      - git-lfs
    state: latest

- name: Install Phoronix test suite prerequisites
  ansible.builtin.apt:
    name:
      - php-cli
      - php-xml
    state: latest

- name: Install work development packages
  ansible.builtin.apt:
    name:
      - libunittest++-dev
      - libarchive-dev
      - libssl-dev
      - libsqlite3-dev
      - bc
    state: latest

- name: Install Python development packages
  ansible.builtin.apt:
    name:
      - python3
      - python3-grpc-tools
      - python3-venv
      - python3-pip
      - pylint
      - bandit
      - black
    state: latest
