---
- name: Set hostname
  ansible.builtin.hostname:
    name: "{{ inventory_hostname }}"

- name: Create ansible user
  ansible.builtin.user:
    name: ansible

- name: Allow Ansible user to sudo
  ansible.builtin.lineinfile:
    path: /etc/sudoers.d/ansible-allow-to-sudo
    state: present
    line: "ansible ALL=(ALL) NOPASSWD: ALL"
    validate: /usr/sbin/visudo -cf %s
    owner: root
    group: root
    mode: '0644'
    create: true

- name: Install ZSH
  ansible.builtin.apt:
    name: zsh
    state: present

- name: Set shell to ZSH
  ansible.builtin.user:
    name: jonny
    shell: /usr/bin/zsh

- name: Get GRML ZSH
  ansible.builtin.get_url:
    url: https://git.grml.org/f/grml-etc-core/etc/zsh/zshrc
    dest: /home/jonny/.zshrc
    owner: jonny
    group: jonny

- name: Add local ZSH config
  ansible.builtin.copy:
    src: zshrc.local
    dest: /home/jonny/.zshrc.local
    owner: jonny
    group: jonny
