---
- name: Set hostname
  ansible.builtin.hostname:
    name: "{{ inventory_hostname }}"
  when: inventory_hostname != "localhost"

- name: Create ansible user
  ansible.builtin.user:
    name: ansible

- name: Allow Ansible user to sudo
  ansible.builtin.lineinfile:
    path: /etc/sudoers.d/ansible-allow-to-sudo
    state: present
    line: "ansible ALL=(ALL) NOPASSWD: ALL"
    validate: /usr/sbin/visudo -cf %s
    owner: root
    group: root
    mode: '0644'
    create: true

- name: Install ZSH
  ansible.builtin.apt:
    name: zsh
    state: present

- name: Install common tools
  ansible.builtin.apt:
    name:
      - unzip
    state: present

- name: Configure my user
  ansible.builtin.user:
    name: jonny
    uid: 1000
    groups: sudo
    append: true
    shell: /usr/bin/zsh

- name: Get GRML ZSH
  ansible.builtin.get_url:
    url: https://git.grml.org/f/grml-etc-core/etc/zsh/zshrc
    dest: /home/jonny/.zshrc
    owner: jonny
    group: jonny

- name: Copy configs
  ansible.builtin.copy:
    src: "{{ item }}"
    dest: /home/jonny/.{{ item }}
    owner: jonny
    group: jonny
  with_items:
    - zshrc.local
    - gitconfig
