---

- name: Install docker
  ansible.builtin.apt:
    name: docker.io
    state: present
  when: not docker_external

- name: Install docker from repo
  include_tasks: docker-external.yml
  when: docker_external

- name: Install Python 3 docker
  package:
    name: python3-docker
  when: ansible_python.version.major == 3

- name: Install Python 2 docker
  package:
    name: python-docker
  when: ansible_python.version.major == 2

- name: Start docker
  ansible.builtin.service:
    name: docker
    enabled: true
    state: started

- name: Add jonny to docker group
  ansible.builtin.user:
    name: jonny
    groups: docker
    append: true

- name: Create container configuration directory
  ansible.builtin.file:
    path: "{{ container_config_folder }}"
    state: directory
    mode: '0755'
