---

- name: Install docker
  ansible.builtin.apt:
    name:
      - docker.io
      - python3-docker
    state: present

- name: Start docker
  ansible.builtin.service:
    name: docker
    enabled: true
    state: started

- name: Add jonny to docker group
  ansible.builtin.user:
    name: jonny
    groups: docker
    append: true
