---

- name: Create traefik network
  community.docker.docker_network:
    name: "{{ traefik_network_name }}"

- name: Start traefik container
  community.docker.docker_container:
    name: traefik
    image: traefik:v2.4.8
    pull: true
    command:
      - --api.insecure=true
      - --entrypoints.web.address=:80
      - --providers.docker.exposedbydefault=true
    state: started
    restart_policy: unless-stopped
    networks:
      - name: "{{ traefik_network_name }}"
    published_ports:
      - "80:80"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    labels:
      traefik.http.routers.api.rule: Host(`monitor.{{ inventory_hostname }}`)
      traefik.http.routers.api.service: api@internal
    container_default_behavior: no_defaults
    network_mode: "{{ traefik_network_name }}"
    auto_remove: false
    init: false
    interactive: false
    memory: "0"
    paused: false
    privileged: false
    tty: false
