---
- name: Configuration for emmas-edit
  hosts: ssh.emmasedit.com
  roles:
    - {role: common, vars: {inventory_hostname: emmasedit.com}}
    - {role: sshd}
    - {role: docker, vars: {docker_external: true}}
    - {role: wordpress}
    - {role: unattended-upgrades}
