---
- name: Configuration for pi-hole
  hosts: pi.hole
  roles:
    - {role: common}
    - {role: sshd}
    - {role: docker, vars: {docker_external: true, docker_arch: armhf}}
    - {role: unattended_upgrades}
    - {role: cloudflared}
    - {role: pi_hole}
