---

- name: Check for sshd config snippet support
  ansible.builtin.stat:
    path: /etc/ssh/sshd_config.d
  register: ssh_dir

- name: Copy sshd config snippets
  ansible.builtin.copy:
    src: "{{ item }}"
    dest: /etc/ssh/sshd_config.d/{{ item }}
    owner: root
    group: root
  with_items:
    - 00-allowed-users.conf
    - 10-harden.conf
  when: ssh_dir.stat.exists
  notify: restart ssh

- name: Push authorized keys
  ansible.posix.authorized_key:
    user: jonny
    key: "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIGOARhByqvHhJYkOvn+1IlEnKsnn3aqNNFXervuw/Qq+ jonny@pattern-2021-03-10"
