---

- name: Check for sshd config snippet support
  ansible.builtin.stat:
    path: /etc/ssh/sshd_config.d
  register: ssh_dir

- name: Copy sshd config snippets
  ansible.builtin.copy:
    src: "{{ item }}"
    dest: /etc/ssh/sshd_config.d/{{ item }}
    owner: root
    group: root
  with_items:
    - 00-allowed-users.conf
    - 10-harden.conf
  when: ssh_dir.stat.exists
  notify: restart ssh

- name: Push authorized keys
  ansible.posix.authorized_key:
    user: jonny
    key: "{{ item }}"
  with_items: "{{ ssh_keys }}"

- name: Push ansible authorized keys
  ansible.posix.authorized_key:
    user: ansible
    key: "{{ item }}"
  with_items: "{{ ssh_keys }}"
