---
name: Lint

# yamllint disable-line rule:truthy
on: [push]

jobs:
  shellcheck:
    name: Shellcheck
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2.3.4
        with:
          fetch-depth: 1
      - name: Run ShellCheck
        uses: ludeeus/action-shellcheck@1.1.0
        with:
          scandir: './one-shots'
  yaml:
    name: YAMLlint
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2.3.4
        with:
          fetch-depth: 1
      - name: Lint YAML
        uses: ibiqlik/action-yamllint@v3.0.0
        with:
          strict: true
          config_file: .yamllint.yml
  ansible:
    name: Ansible Lint
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2.3.4
        with:
          fetch-depth: 1
      - name: Lint Ansible
        uses: ansible/ansible-lint-action@master
        with:
          targets: "playbooks/*.yml"
